# 공통 설정 (모든 서비스에서 override)
spring:
  cloud:
    config:
      # 서비스별 설정에서 공통 설정을 덮어쓸 수 있음
      # true : config server 에서 받은 설정이 로컬 설정으로 덮어써 짐
      # false : config server 설정이 우선, 로컬 설정은 무시됨
      allow-override: true
      # JVM 시스템 프라퍼티를 덮어쓸수 있는가
      # true : -D 옵션으로 부여한 시스템 프라퍼티보다 우선 적용
      # false : 시스템 프라퍼티를 최우선으로 유지
      override-system-properties: false
    discovery:
      enabled: true

  main:
    # true : 동일한 이름의 Bean이 여러개 일때 마지막 정의가 덮어씀.
    # false (default) : 어플리케이션 로딩 시 오류
    allow-bean-definition-overriding: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO