server.port: 8081
spring:
  application:
    name: user
  config:
    import: "optional:configserver:http://config.project.local:8888"
  cloud:
    config:
      fail-fast: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka.project.local:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
