server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  client:
    # eureka 에 등록할지 (자기 자신을 등록하지 않음)
    register-with-eureka: false
    # 다른 서비스 조회 여부
    fetch-registry: false
    # eureka 서버 주소 (eureka 가 다중 서버로 구성되는 경우에 필요)
    service-url:
      defaultZone: http://localhost:8761/eureka/

  # 단일 서버일때 localhost 다중서버일때 중요
  instance:
    hostname: localhost