server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  client:
    register-with-eureka: false # standalone
    fetch-registry: true # 다른 서비스들의 레지스트리 정보를 가져옴
  server:
    enable-self-preservation: false # 죽은 서비스 제거